---
- extensions:
  - default: false
  - name: [DeriveDataTypeable, DeriveFunctor, GeneralizedNewtypeDeriving, NoMonomorphismRestriction, OverloadedStrings]
  - name: [MultiWayIf, PatternGuards, RecordWildCards, ViewPatterns, PatternSynonyms, TupleSections, LambdaCase]
  - name: [Rank2Types, ScopedTypeVariables]
  - name: [ExistentialQuantification, MultiParamTypeClasses, NamedFieldPuns]
  - name: [FlexibleContexts, FlexibleInstances]
  - name: [PackageImports]
  - name: [ConstraintKinds, RankNTypes, TypeFamilies]
  - name: [TemplateHaskell]
  - {name: CPP, within: [HsColour]} # so it can be disabled to avoid GPL code

- flags:
  - default: false
  - {name: [-Wno-missing-fields, -fno-cse, -O0], within: CmdLine} # for cmdargs
  - {name: [-Wno-incomplete-patterns, -Wno-overlapping-patterns]} # the pattern match checker is not very good

- modules:
  - {name: [Data.Set, Data.HashSet], as: Set}
  - {name: [Data.Map, Data.HashMap.Strict, Data.HashMap.Lazy], as: Map}
  - {name: Control.Arrow, within: []}

- functions:
  - {name: unsafeInterleaveIO, within: Parallel}
  - {name: unsafePerformIO, within: [Util.exitMessageImpure, Test.Util.ref, Timing]}
  - {name: unsafeCoerce, within: [Util.gzip, GHC.Util.Refact.Utils]}
  - {name: nub, within: []}

- warn: {name: Use explicit module export list}


- error: {lhs: QVarOp a (UnQual b x), rhs: toNamed x}
- error: {lhs: QConOp a (UnQual b x), rhs: toNamed x}
- error: {lhs: UnQual a (Symbol b x), rhs: toNamed x}
- error: {lhs: UnQual a (Ident  b x), rhs: toNamed x}
- error: {lhs: Var a (toNamed x), rhs: toNamed x}
- error: {lhs: Con a (toNamed x), rhs: toNamed x}

- error: {lhs: idea Warning, rhs: warn}
- error: {lhs: idea Suggestion, rhs: suggest}
- error: {lhs: ideaN Warning, rhs: warnN}
- error: {lhs: ideaN Suggestion, rhs: suggestN}


  # would require module cycles
- ignore: {name: Use toNamed, within: HSE.Util}
  # doesn't fit with the other statements
- ignore: {name: Use let, within: [HLint, Test.All]}
  # would be a lot of is/from exports
- ignore: {name: Use explicit module export list, within: HSE.Util}

- ignore: {name : Redundant bracket}
- ignore: {name : Use print}
- ignore: {name : Redundant $}
- ignore: {name : Use fewer imports}
- ignore: {name : Avoid restricted extensions}

