FROM lnl7/nix:2.3.3
# If you change this on qwde.no, rebuild the image manually with docker build -t qwdefrontend:deps . -f Dockerfile_build

RUN nix-env -iA \
        nixpkgs.curl \
        nixpkgs.jq \
        nixpkgs.git \
        nixpkgs.gnutar \
        nixpkgs.gzip \
        # get ca certificates for connecting to cachix
        nixpkgs.libressl \
        # install ag and entr for auto-rebuild
        nixpkgs.silver-searcher \
        nixpkgs.entr \
        nixpkgs.cabal-install

RUN nix-env -iA cachix -f https://cachix.org/api/v1/install
RUN SYSTEM_CERTIFICATE_PATH=$NIX_SSL_CERT_FILE USER=miso cachix use miso-haskell
COPY shell.nix release.nix dependencies.nix cabal.project hie.yaml Setup.hs /qwde/
COPY nix/ /qwde/nix/
WORKDIR /qwde/
RUN nix-build dependencies.nix
