micronaut:
  application:
    name: qwde
  server:
    port: 8080
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**.js"
        paths: "classpath:public"
jackson:
  serialization-inclusion: NON_ABSENT # Omit null and Optional.empty(), but include empty collections
  serialization:
    indent-output: true # Pretty-print JSON
