micronaut:
  application:
    name: qwde
  server:
    port: 8080
    netty:
      log-level: TRACE
    cors:
      logger:
        levels:
          root: TRACE
      enabled: true
      configurations:
        all:
          allowedOrigins:
            - http://localhost:8081
            - http://localhost:8080
            - http://qwde.no:8081
          allowedMethods:
            - GET
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

jackson:
  serialization-inclusion: NON_ABSENT # Omit null and Optional.empty(), but include empty collections
  serialization:
    indent-output: true # Pretty-print JSON
